baseurl = "https://my-b5.kora.win/"
languageCode = "ja"

hasCJKLanguage = true
defaultContentLanguageInSubdir = true
defaultContentLanguage = "ja"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap-5"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
# googleAnalytics = ""

[languages]
[languages.ja]
  languageName = "日本語"
  languageCode = "ja"
  # contentDir = "content/ja"
  weight = 1

  title = "水城卓球スクール"
  dateFormat = "2006年01月02日"

  [[languages.ja.menu.main]]
    url = "/"
    pre = '<i class="fa-solid fa-house"></i>'
    name = "ホーム"
    weight = 1
  [[languages.ja.menu.main]]
    url = "/school/"
    pre = '<i class="fa-solid fa-school"></i>'
    name = "教室紹介"
    weight = 2
  [[languages.ja.menu.main]]
    url = "/stuff/"
    pre = '<i class="fa-solid fa-user-tie"></i>'
    name = "スタッフ"
    weight = 3
  [[languages.ja.menu.main]]
    url = "/schedule/"
    pre = '<i class="fa-solid fa-calendar-days"></i>'
    name = "スケジュール"
    weight = 4
  [[languages.ja.menu.main]]
    url = "/post/"
    pre = '<i class="fa-solid fa-person-running"></i>'
    name = "活動報告"
    weight = 5
  [[languages.ja.menu.main]]
    url = "/access/"
    pre = '<i class="fa-solid fa-location-dot"></i>'
    name = "アクセス"
    weight = 6
  [[languages.ja.menu.main]]
    url = "/contact/"
    pre = '<i class="fa-solid fa-square-phone-flip"></i>'
    name = "お問合せ"
    weight = 7

[languages.en]
  languageName = "English"
  languageCode = "en"
  # contentDir = "content/en"
  weight = 51

  title = "Mizuki Table Tennis School"
  dateFormat = "2006-01-02"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with 笶､ by Xzya"

  [[languages.en.menu.main]]
    url = "/en/"
    name = "Home"
    weight = 52
  [[languages.en.menu.main]]
    url = "/en/about/"
    name = "About"
    weight = 53
